config/bootstrap.php, src/Controller/MessagesController.php, src/Event/Model/TranslationsAfterSaveEventsListener.php, src/Model/Table/MessagesTable.php, src/Template/Cell/Inbox/unread_messages.ctp, src/Template/Element/unread_messages.ctp, src/Template/Messages/view.ctp, src/View/Cell/InboxCell.php
Add basic Event Listener functionality
=> Messaging Center plugin (task #1495)

.editorconfig, .travis.yml, src/Controller/MessagesController.php, src/Template/Element/sidebar.ctp, src/Template/Element/user.ctp, src/Template/Messages/compose.ctp, src/Template/Messages/folder.ctp, src/Template/Messages/view.ctp, webroot/css/style.css
* Improved display of the message user (to/from)
* Improved folder message listing (table headers, styling of new messages)
* Improved view message display (message headers)
* Added pencil icon to the Compose button
* Merged [cakephp-plugin-template v2.0.0](https://github.com/QoboLtd/cakephp-plugin-template/releases/tag/v2.0.0)
=> Minor improvements

tests/App/Controller/AppController.php, tests/App/Controller/UsersController.php, tests/App/Template/Error/error400.ctp, tests/App/Template/Error/error500.ctp, tests/App/Template/Layout/default.ctp, tests/App/Template/Users/login.ctp, tests/Fixture/UsersFixture.php, tests/TestCase/Model/Table/MessagesTableTest.php, tests/bootstrap.php, tests/config/routes.php, tests/test_app/config/routes.php
Merged [cakephp-plugin-template v3.0.0](https://github.com/QoboLtd/cakephp-plugin-template/releases/tag/v3.0.0).
=> Template update

config/bootstrap.php
Prevent overwriting of app level config by the plugin config, if the app level config was loaded before the plugin.
=> Plugin Configuration (task #2719)

src/Model/Behavior/NotifyBehavior.php
Add support for notifications for new entities.
=> Notifications for new Entities (task #2719)

composer.json
Upgrading CakeDC/Users plugin version
=> Upgrading CakeDC/Users plugin

src/Template/Cell/Inbox/unread_messages.ctp, src/Template/Element/unread_messages.ctp, src/View/Cell/InboxCell.php
* Modified unread message cell template to match AdmiLTE layout
* Removed obsolete element
=> AdminLTE unread messages (task #3151)

src/Controller/MessagesController.php, src/Template/Element/sidebar.ctp, src/Template/Messages/compose.ctp, src/Template/Messages/folder.ctp, src/Template/Messages/reply.ctp, src/Template/Messages/view.ctp, webroot/css/style.css
Changed `composer.ctp`, `reply.ctp` and `view.ctp` templates layout and styling to match AdminLTE
=> Templates layout and styling (task #3151)

src/Model/Behavior/NotifyBehavior.php, src/Template/Messages/folder.ctp
- Update messages index View to include table headers
- Moved unread icon into its own table column
- Removed message content excerpt
- Broadcast event to modify notification message before rendering it
=> UI Improvements (task #3282)

composer.json
Updated to [cakephp-utils v3+](https://github.com/QoboLtd/cakephp-utils/releases/tag/v3.0.0).
=> Updated to cakephp-utils v3+ (task #3495)

config/messaging_center.php, src/Event/UserListener.php, src/Template/Notifier/welcome.ctp
remove try - catch, change projectName configuration value, edit welcome message
=> change projectName configuration value

src/Model/Table/MessagesTable.php
Fixing issues identified by PHPStan
=> Minor docblock fix

.codeclimate.yml, .travis.yml, LICENSE, src/Template/Messages/compose.ctp, src/Template/Messages/folder.ctp, src/Template/Messages/reply.ctp
Updated to [cakephp-plugin-template v4.1.0](https://github.com/QoboLtd/cakephp-plugin-template/releases/tag/v4.1.0).
=> Updated to cakephp-plugin-template v4.1.0

config/Migrations/20181206083415_CreateMailboxes.php, config/Migrations/20181206083430_CreateFolders.php, config/Migrations/20181206165004_AddFolderToMessage.php, config/Migrations/20181206165021_CreateMessagesUsersStatuses.php, src/Event/EventName.php, src/Event/Model/MailboxListener.php, src/Model/Entity/Folder.php, src/Model/Entity/Mailbox.php, src/Model/Table/FoldersTable.php, src/Model/Table/MailboxesTable.php, src/Model/Table/MessagesTable.php, src/Notifier/Notifier.php, tests/Fixture/FoldersFixture.php, tests/Fixture/MailboxesFixture.php, tests/TestCase/Model/Table/FoldersTableTest.php, tests/TestCase/Model/Table/MailboxesTableTest.php, tests/TestCase/Model/Table/MessagesTableTest.php
- added new table to keep mailboxes
- added new table to keep folders
- added new table to keep statuses of messages for each user
- extended table with messages to have relations with folders
=> Add mailboxes and folders to messaging center (task #8830)

src/Model/Table/MessagesTable.php, tests/Fixture/FoldersFixture.php, tests/Fixture/MailboxesFixture.php, tests/Fixture/MessagesFixture.php, tests/TestCase/Model/Table/FoldersTableTest.php, tests/TestCase/Model/Table/MailboxesTableTest.php, tests/TestCase/Model/Table/MessagesTableTest.php
- improved logic to process messages and assign them to mailboxes and folders - task #9795
=> Fix logic of process of messages (task #9795)

src/Event/Model/MailboxListener.php, src/Event/Model/UserListener.php
Added different priorities to setup system mailbox and folders before sending welcome message for new users - task #9977
=> Fix issue with setup mailbox and send welcome message for new users (task #9977)

phpstan.neon.dist, src/Controller/MessagesController.php, src/Event/Model/MailboxListener.php, src/Model/Table/FoldersTable.php, src/Model/Table/MailboxesTable.php, src/Model/Table/MessagesTable.php, src/Notifier/MessageNotifier.php, src/Notifier/Notifier.php
Replaces var annotations with assertions
=> Replace var annotations (task #9606)

src/Shell/FetchMailShell.php
It catches BADCHARSET (US-ASCII) Exception and retries searching without using the server encoding.
=> Improved Office 365 / Exchange support (task #9063)

src/Model/Table/MessagesTable.php, src/Shell/FetchMailShell.php
This PR introduces two options for email fetcher that can be used to filter the incoming messages:
* `--since=today` fetch email since the provided date
* `--limit=100` fetch the last 100 messages only
Also:
* Always prefer Text over HTML. If Text can not be found, the HTML is stripped from script / style tags before saving
=> [WIP] Email fetcher options (task #11988)

src/Model/Table/MailboxesTable.php, src/Model/Table/MessagesTable.php
Added back the associations that have been removed so that we can see the permission  for the from_user and to_user
=> Add associations with CakeDC/Users.Users (Task #11967)

src/Model/Table/MessagesTable.php
Messages with empty subject will be saved
=> Allow empty subject messages to be saved (Task #11324)

src/Controller/MessagesController.php, tests/TestCase/Controller/MessagesControllerTest.php
Will retrieve all messages attachments and expose them in the view method
=> Retrieve message attachments (Task #11323)

tests/Fixture/FoldersFixture.php, tests/Fixture/MailboxesFixture.php
This PR improves the existing fixtures by adding mailbox and folders for user-1
=> More fixtures (task #12077)

src/Controller/MessagesController.php, src/Model/Entity/Message.php, tests/TestCase/Controller/MessagesControllerTest.php
This PR removes some hardcoded permissions while corrects the checks in regards to sent messages.
=> Permissions (task #11967) 

.gitignore, phpcs.xml.dist, src/Controller/FoldersController.php
Merged cakephp-plugin-template v5.2.5
=> Merged cakephp-plugin-template v5.2.5

src/Controller/MessagesController.php, src/Model/Table/MessagesTable.php, src/Template/Messages/reply.ctp, tests/TestCase/Controller/MessagesControllerTest.php
This PR fixes the reply button. The result should be 2 more messages one in the sender's Sent folder and the other to recipient's inbox folder
=> Fix reply button (Task #14027)

src/Controller/FoldersController.php, src/Controller/MailboxesController.php, src/Controller/MessagesController.php, src/Locale/MessagingCenter.pot, src/Model/Table/MailboxesTable.php, src/Template/Element/compose_message.ctp, src/Template/Element/mailbox_form.ctp, src/Template/Element/messages_list.ctp, src/Template/Element/unread_count.ctp, src/Template/Folders/add.ctp, src/Template/Folders/edit.ctp, src/Template/Folders/index.ctp, src/Template/Folders/view.ctp, src/Template/Mailboxes/add.ctp, src/Template/Mailboxes/edit.ctp, src/Template/Mailboxes/index.ctp, src/Template/Mailboxes/view.ctp, src/Template/Messages/compose.ctp, src/Template/Messages/folder.ctp, src/Template/Messages/reply.ctp, src/Template/Messages/view.ctp
This PR updates translation and added localization files
=> Translations for cakephp-messaging-center (Task #14427)

config/messaging_center.php, src/Controller/FoldersController.php, src/Controller/MailboxesController.php, src/Controller/MessagesController.php, src/Event/Model/MailboxListener.php, src/Event/Model/SendEmailListener.php, src/Event/Model/UserListener.php, src/Model/Behavior/NotifyBehavior.php, src/Model/Entity/Folder.php, src/Model/Entity/Mailbox.php, src/Model/MessageFactory.php, src/Model/Table/FoldersTable.php, src/Model/Table/MailboxesTable.php, src/Model/Table/MessagesTable.php, src/Notifier/Notifier.php, src/View/Cell/InboxCell.php, tests/App/Controller/AppController.php, tests/Fixture/ArticlesFixture.php, tests/Fixture/FoldersFixture.php, tests/Fixture/MailboxesFixture.php, tests/Fixture/MessagesFixture.php, tests/TestCase/Controller/FoldersControllerTest.php, tests/TestCase/Controller/MessagesControllerTest.php, tests/TestCase/Model/Behavior/NotifyBehaviorTest.php, tests/bootstrap.php
PHPCS fixes to accommodate with the recent PSR-12 adoption.
=> Fix phpcs errors

src/Event/EventName.php, src/Notifier/MessageNotifier.php, tests/TestCase/Model/Behavior/NotifyBehaviorTest.php
This PR adds an event dispatch for notifying that a message has been created
=> Dispatch event for Notifications (Task #15648)

src/Template/Notifier/record_link.ctp, src/Template/Notifier/record_modified.ctp
remove url prefix to avoid wrong link on API request
=> Fix email template from API (task #17461)
